# Generated by Django 5.2.7 on 2025-11-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_department_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d/'),
        ),
    ]
