# Generated by Django 5.2.7 on 2025-11-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customusermodel_options_customusermodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='password_time_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
