# Generated by Django 5.2.7 on 2025-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_role_department_role_group_delete_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='role',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.role'),
        ),
    ]
