# Generated by Django 5.2.7 on 2025-11-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customusermodel_role_customusermodel_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
