# Generated by Django 5.2.7 on 2025-11-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_is_verfied_customusermodel_is_verified'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_f8d50d_idx'),
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['email'], name='accounts_cu_email_6692c4_idx'),
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['is_active'], name='accounts_cu_is_acti_ec1a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['manager'], name='accounts_cu_manager_c3ca6f_idx'),
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['is_active', 'manager'], name='accounts_cu_is_acti_9b72c6_idx'),
        ),
    ]
