# Generated by Django 5.2.7 on 2025-11-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customusermodel_accounts_cu_usernam_f8d50d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customusermodel',
            name='accounts_cu_is_acti_ec1a1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='customusermodel',
            name='accounts_cu_manager_c3ca6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='customusermodel',
            name='accounts_cu_is_acti_9b72c6_idx',
        ),
    ]
