# Generated by Django 5.2.7 on 2025-11-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customusermodel_accounts_cu_is_acti_ec1a1e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.ManyToManyField(blank=True, to='accounts.role'),
        ),
    ]
